// The answer pipeline — docs/19 W1.
//
// This logic used to live inside GameContext and could not be tested without a
// renderer. It is the most consequential function in the product: everything
// the engine believes about a learner is derived from the sequence of calls
// made here. These tests are the ones that were impossible before.

import { describe, it, expect } from 'vitest';
import { recordAnswer, type AnswerState, type AnswerEvent } from '../recordAnswer';
import type { Question } from '../../generators/types';
import { MASTERED_THRESHOLD } from '../../learning/mastery';

const NOW = 1_700_000_000_000;

const q = (over: Partial<Question> = {}): Question => ({
  questionText: '43 − 27 = ?', answer: 16, choices: [16, 24, 14, 26], ...over,
});

const empty: AnswerState = { log: [], ledger: {}, totalXp: 0 };

const ev = (over: Partial<AnswerEvent> = {}): AnswerEvent => ({
  question: q(), chosen: '16', correct: true, latencyMs: 5000, timedOut: false,
  plannedSkill: 'sub.2digit.borrow', cls: '2nd', sessionCategory: 'subtraction',
  difficulty: 'medium', isTablesMode: false, now: NOW, ...over,
});

describe('the pipeline is pure', () => {
  it('never mutates the state it is given', () => {
    const state: AnswerState = { log: [], ledger: {}, totalXp: 100 };
    const frozen = JSON.stringify(state);
    recordAnswer(state, ev());
    expect(JSON.stringify(state)).toBe(frozen);
  });

  it('is deterministic for the same inputs', () => {
    const a = recordAnswer(empty, ev());
    const b = recordAnswer(empty, ev());
    expect(a.award.total).toBe(b.award.total);
    expect(a.attempt).toEqual(b.attempt);
    expect(a.state.totalXp).toBe(b.state.totalXp);
  });

  it('performs no I/O — the caller decides what to persist', () => {
    // Expressed as: the function is callable with no globals stubbed.
    expect(() => recordAnswer(empty, ev())).not.toThrow();
  });
});

describe('XP is counted exactly once', () => {
  it('does not double-count when called twice with the same input', () => {
    // The regression this guards: XP was computed inside a setState updater,
    // which React may invoke twice (StrictMode, concurrent rendering). That
    // would have double-paid and corrupted the high-water ledger. As a pure
    // function, calling twice from the SAME state must give the same result —
    // it is the caller's job to thread state forward exactly once.
    const first = recordAnswer(empty, ev());
    const again = recordAnswer(empty, ev());
    expect(again.state.totalXp).toBe(first.state.totalXp);
    expect(again.state.ledger).toEqual(first.state.ledger);
  });

  it('accumulates correctly when state is threaded forward', () => {
    let s = empty;
    const totals: number[] = [];
    for (let i = 0; i < 5; i++) {
      const r = recordAnswer(s, ev({ now: NOW + i * 60_000 }));
      s = r.state;
      totals.push(s.totalXp);
    }
    // Monotonically non-decreasing, and strictly increasing while mastery moves.
    for (let i = 1; i < totals.length; i++) {
      expect(totals[i]).toBeGreaterThanOrEqual(totals[i - 1]);
    }
    expect(totals[totals.length - 1]).toBeGreaterThan(0);
  });

  it('pays nothing for a wrong answer, and takes nothing away', () => {
    const r = recordAnswer({ ...empty, totalXp: 500 }, ev({ correct: false, chosen: '24' }));
    expect(r.award.total).toBe(0);
    expect(r.state.totalXp).toBe(500);
  });
});

describe('diagnosis', () => {
  it('prefers the distractor map over inference', () => {
    // A wrong option generated BY a known misconception is a direct
    // observation; inferring from the number would be a weaker claim.
    const r = recordAnswer(empty, ev({
      correct: false, chosen: '24',
      question: q({ distractorMap: { '24': 'sub.smaller-from-larger' } }),
    }));
    expect(r.misconception).toBe('sub.smaller-from-larger');
  });

  it('falls back to inference when there is no map', () => {
    const r = recordAnswer(empty, ev({ correct: false, chosen: '24' }));
    expect(r.misconception).toBe('sub.smaller-from-larger');
  });

  it('never diagnoses a correct answer', () => {
    expect(recordAnswer(empty, ev()).misconception).toBeNull();
  });

  it('never diagnoses a timeout', () => {
    const r = recordAnswer(empty, ev({ correct: false, chosen: '', timedOut: true }));
    expect(r.misconception).toBeNull();
  });
});

describe('the recorded attempt', () => {
  it('uses the scheduler-planned skill when there is one', () => {
    expect(recordAnswer(empty, ev({ plannedSkill: 'mul.tables.mid' })).attempt.skill)
      .toBe('mul.tables.mid');
  });

  it('resolves a skill when the session was manual', () => {
    const r = recordAnswer(empty, ev({ plannedSkill: null }));
    expect(r.attempt.skill).toBe('sub.2digit.borrow');
  });

  it('attributes a Mixed question to its resolved category, not "mixed"', () => {
    const r = recordAnswer(empty, ev({
      sessionCategory: 'mixed',
      question: q({ resolvedCategory: 'subtraction' }),
    }));
    expect(r.attempt.category).toBe('subtraction');
  });

  it('records the interaction kind, so recognition is distinguishable from recall', () => {
    expect(recordAnswer(empty, ev()).attempt.interaction).toBe('choice');
    expect(recordAnswer(empty, ev({
      question: q({ interaction: { kind: 'entry', inputMode: 'integer' } }),
    })).attempt.interaction).toBe('entry');
  });

  it('records scaffolding, so support cannot inflate mastery', () => {
    expect(recordAnswer(empty, ev({ scaffolded: true })).attempt.scaffolded).toBe(true);
    expect(recordAnswer(empty, ev()).attempt.scaffolded).toBeUndefined();
  });

  it('uses the injected clock rather than wall time', () => {
    expect(recordAnswer(empty, ev({ now: 42 })).attempt.answeredAt).toBe(42);
  });
});

describe('mastery movement drives the payout', () => {
  it('reports mastery before and after', () => {
    const r = recordAnswer(empty, ev());
    expect(r.masteryAfter).toBeGreaterThan(r.masteryBefore);
  });

  it('pays little once a skill is already secure', () => {
    // Grinding a mastered skill must be worth almost nothing — the core claim
    // of the whole economy.
    let s = empty;
    for (let i = 0; i < 40; i++) {
      s = recordAnswer(s, ev({
        now: NOW + i * 60_000,
        question: q({ interaction: { kind: 'entry', inputMode: 'integer' } }),
      })).state;
    }
    const before = s.totalXp;
    const r = recordAnswer(s, ev({ now: NOW + 100 * 60_000 }));
    expect(r.masteryBefore).toBeGreaterThan(MASTERED_THRESHOLD);
    expect(r.state.totalXp - before).toBeLessThan(5);
  });
});

describe('derived views stay consistent with the log', () => {
  it('recomputes the legacy aggregate on every answer', () => {
    let s = empty;
    for (let i = 0; i < 6; i++) {
      s = recordAnswer(s, ev({ now: NOW + i * 1000, correct: i % 2 === 0 })).state;
    }
    const r = recordAnswer(s, ev({ now: NOW + 7000 }));
    const key = '2nd_subtraction_medium';
    expect(r.progressStats[key].attempted).toBe(7);
    expect(r.progressStats[key].correct).toBe(4);
  });
});
